
function HealthRecordEmpty(){

    //THE LOGIC OF CHECKING THAT THIS PATIENT WE JUST CLICKED HIS(HEALTH RECORD)BUTTON DOES NOT ACTUALLY HAVE ONE YET, AND DISPLAYING A MESSAGE THAT THIS PATIENT DOES NOT HAVE A HEALTH RECORD YET AND AN OPTION (+) BUTTON TO ADD 

    //return
    //THE VIEW 
    //A SIMPLE MESSEGE IN THE MIDDLE OF THE SCREEN AND A PLUS BUTTON THAT REDIRECT TO THE (HEALTH RECORD FORM) PAGE
}

export default HealthRecordEmpty;