
function HealthRecordForm(){
    //THE LOGIC OF DISPLAYING A FORM TO TAKE UP ALL THE INFORMATION NEEDED TO ADD A NEW HEALTH RECORD OF A SPECIFIC PATIENT UPON CLICK ON THAT BUTTON(+) IN THE (EMPTY HEALTH RECORD)PAGE

    //ALSO HANDLING SUBMIT OF THAT BUTTON
    //SHOULD REDIRECT TO THE (HEALTH RECORD) PAGE OF THAT PATIENT AND DISPLAY IT THERE OR REDIRECT TO THE (MY PATIENTS) PAGE WITH JUST A NOTIFICATION THAT HEALTH RECORD IS ADDED SUCCESSFULLY AND THE DOCTOR COULD CLICK ON THE HEALTH RECORD BUTTON AGAIN TO VIEW (STILL THINKING)

    //return
    //THE DISPLAY OF THE FORM
    //SIMPLE FORM, MAKE SURE IT INCLUDES ALL  THE QUESTIONS NEEDED TO GATHER THE INFO FOR CREATE HEALTH RECORD, GIVE SPACE FOR (NO ANSWER), INCLUDE BUTTONS TO UPLOAD IMAGES WHEN NEEDED, INCLUDE A GENERAL COMMENTS(NOTES) SECTION 

}

export default HealthRecordForm;