
function HealthRecord(){

    //THE LOGIC OF VIEWING THE HEALTH RECORD OF A SPECIFIC PATIENT IF HAS ONE

    //HANDELING THE MANY UPDATES BUTTON THAT A DOCTOR COULD ADD SOME NEW COMMENTS AND UPLOAD NEW IMAGES, EDIT INFO


    //return
    //THE VIEW 
    //DISPLAYING SECTIONS OF THE HEALTH RECORD IN A PROPER WAY AND DIPLAYING IMAGES AND NOTES 
}

export default HealthRecord;