
function PatientsInfo(){
    //THE LOGIC OF GETTING A CERTAIN PATIENTS INFO UPON CLICK

    //return
    //THE DISPLAY OF THAT INFO
    //JUST A LITTLE CARD IN THE MIDDLE OF THE PAGE CONTAINS ALL INFO OF THE PATIENT


}

export default PatientsInfo;